### ISSUE TITLE
Hunger Games Collection Help

### ISSUE THREAD

**Issue by XBadFellaX** [mrbuckwheet/Kometa-Config#6]
Hello Friend,

Thanks for this repo. I used your config and ran it against my library. It is working like a charm but it wouldn't create the Hunger Games collection for me even though I have 4 movies of those.

Can you guide me on how to do that with your config? I have looked it up online and it says I need to specify Franchise in the config somewhere but I am confused with the Movie Collections file that is where to do that config file or the other one.

This initial help is appreciated, thanks.

**Comment by mrbuckwheet** [comment]
If you would like to add a Hunger Games Universe there are instructions in the universe tab that allow you to add your own lists that are not included with the default Kometa data set.

```
 - default: universe
      template_variables:
        use_separator: false
          #append_data:     # this adds custom lists from imdb, trakt, or mdb
            #customnamehere: Title of my Custom List   # name of custom collection. You can abbreviate the "customnamehere" to anything you want ie austinpow, quenttara
          #imdb_list_customnamehere: https://www.imdb.com/list/lsXXXXXXXXXXXXXXXX/   # link to imdb list. You can also use mdblist_list_<<key>>, or trakt_list_<<key>> of those website lists
          #url_poster_customnamehere: https://www.website.com/jpg # poster url  
```

**Comment by XBadFellaX** [comment]
Thanks, I somehow added the franchise variable and now I have doubles. Let me clean this up.

![image](https://github.com/user-attachments/assets/bfc4e2ed-09c4-4cec-9009-92b8c3e864be)
